package business;

import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thebell
 */
public class EditarProjeto extends javax.swing.JFrame {

    private final int index;
    private final Projeto projeto;
    private final ArrayList<Projeto> projetos;

   
    public EditarProjeto(int index, ArrayList<Projeto> projetos) {
        this.index = index;
        this.projeto = projetos.get(index);
        this.projetos = projetos;
        initComponents();
        mostrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEditarProjeto = new javax.swing.JPanel();
        jScrollPaneNovoProjeto = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProjetoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldProjetoCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldProjetoValorTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProjetoDescricao = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxProjetoCliente = new javax.swing.JComboBox<>();
        jTextFieldProjetoCliente = new javax.swing.JTextField();
        jButtonProjetoAdicionar = new javax.swing.JButton();
        jFormattedTextFieldProjetoData = new javax.swing.JFormattedTextField();
        jButtonProjetoSalvar = new javax.swing.JButton();
        jButtonProjtoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Projeto"));

        jLabel1.setText("Nome");

        jTextFieldProjetoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProjetoNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Código");

        jTextFieldProjetoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProjetoCodigoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data");

        jLabel5.setText("Valor total");

        jTextFieldProjetoValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProjetoValorTotalActionPerformed(evt);
            }
        });

        jTextAreaProjetoDescricao.setColumns(20);
        jTextAreaProjetoDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProjetoDescricao);

        jLabel10.setText("Descrição");

        jLabel16.setText("Clientes");

        jComboBoxProjetoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um cliente" }));
        jComboBoxProjetoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxProjetoClienteMouseClicked(evt);
            }
        });
        jComboBoxProjetoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProjetoClienteActionPerformed(evt);
            }
        });

        jTextFieldProjetoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProjetoClienteActionPerformed(evt);
            }
        });

        jButtonProjetoAdicionar.setText("Adicionar");
        jButtonProjetoAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProjetoAdicionarMouseClicked(evt);
            }
        });

        try {
            jFormattedTextFieldProjetoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxProjetoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonProjetoAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldProjetoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldProjetoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldProjetoData))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(121, 121, 121)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextFieldProjetoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldProjetoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jLabel10)
                        .addComponent(jLabel16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProjetoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldProjetoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProjetoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldProjetoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProjetoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProjetoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProjetoAdicionar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButtonProjetoSalvar.setText("Salvar");
        jButtonProjetoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProjetoSalvarMouseClicked(evt);
            }
        });
        jButtonProjetoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjetoSalvarActionPerformed(evt);
            }
        });

        jButtonProjtoCancelar.setText("Cancelar");
        jButtonProjtoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProjtoCancelarMouseClicked(evt);
            }
        });
        jButtonProjtoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjtoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonProjetoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonProjtoCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProjetoSalvar)
                    .addComponent(jButtonProjtoCancelar))
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jScrollPaneNovoProjeto.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanelEditarProjetoLayout = new javax.swing.GroupLayout(jPanelEditarProjeto);
        jPanelEditarProjeto.setLayout(jPanelEditarProjetoLayout);
        jPanelEditarProjetoLayout.setHorizontalGroup(
            jPanelEditarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoProjeto)
        );
        jPanelEditarProjetoLayout.setVerticalGroup(
            jPanelEditarProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoProjeto, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelEditarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelEditarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProjetoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProjetoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjetoNomeActionPerformed

    private void jTextFieldProjetoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProjetoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjetoCodigoActionPerformed

    private void jTextFieldProjetoValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProjetoValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjetoValorTotalActionPerformed

    private void jButtonProjetoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProjetoSalvarMouseClicked
        if (jTextFieldProjetoNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldProjetoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jFormattedTextFieldProjetoData.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldProjetoValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldProjetoCliente.getText().equals("")) { 
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if ((jTextAreaProjetoDescricao.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else {
            projeto.setNome(jTextFieldProjetoNome.getText());
            projeto.setCodigo(Integer.parseInt(jTextFieldProjetoCodigo.getText()));
            projeto.setDataInicio(jFormattedTextFieldProjetoData.getText());
            projeto.setValorTotal(Double.parseDouble(jTextFieldProjetoValorTotal.getText()));
            projeto.setDescricao(jTextAreaProjetoDescricao.getText());
            projeto.setCliente(jTextFieldProjetoCliente.getText());
            projetos.remove(index);
            projetos.add(index, projeto);
            Projeto.escrever(projetos);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
            dispose();
        }

    }//GEN-LAST:event_jButtonProjetoSalvarMouseClicked
     /**
     * Método para preencher os campos do menu com os dados do projeto
     */
    private void mostrar() {
        String pattern = "dd/MM/yyyy";
        DateFormat df = new SimpleDateFormat(pattern);
        String data = df.format(projeto.getDataInicio());
        jTextFieldProjetoNome.setText(projeto.getNome());
        jTextFieldProjetoCodigo.setText(String.valueOf(projeto.getCodigo()));
        jFormattedTextFieldProjetoData.setText(data);
        jTextFieldProjetoValorTotal.setText(String.valueOf(projeto.getValorTotal()));
        jTextAreaProjetoDescricao.setText(projeto.getDescricao());
        jTextFieldProjetoCliente.setText(projeto.getCliente());

    }
    private void jButtonProjetoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjetoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProjetoSalvarActionPerformed

    private void jButtonProjtoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjtoCancelarActionPerformed

    }//GEN-LAST:event_jButtonProjtoCancelarActionPerformed

    private void jButtonProjtoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProjtoCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jButtonProjtoCancelarMouseClicked

    private void jTextFieldProjetoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProjetoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProjetoClienteActionPerformed

    private void jComboBoxProjetoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProjetoClienteActionPerformed

    }//GEN-LAST:event_jComboBoxProjetoClienteActionPerformed

    private void jButtonProjetoAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProjetoAdicionarMouseClicked
        if (jComboBoxProjetoCliente.getSelectedIndex() != -1) {
            jTextFieldProjetoCliente.setText(jComboBoxProjetoCliente.getItemAt(
            jComboBoxProjetoCliente.getSelectedIndex()));
        }
    }//GEN-LAST:event_jButtonProjetoAdicionarMouseClicked

    private void jComboBoxProjetoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProjetoClienteMouseClicked
        ArrayList<Cliente> clientes = Cliente.ler();
        jComboBoxProjetoCliente.removeAllItems();
        
        for (int i = 0; i < clientes.size(); i++) {
            jComboBoxProjetoCliente.addItem(clientes.get(i).getNome());
        }
    }//GEN-LAST:event_jComboBoxProjetoClienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProjetoAdicionar;
    private javax.swing.JButton jButtonProjetoSalvar;
    private javax.swing.JButton jButtonProjtoCancelar;
    private javax.swing.JComboBox<String> jComboBoxProjetoCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldProjetoData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEditarProjeto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneNovoProjeto;
    private javax.swing.JTextArea jTextAreaProjetoDescricao;
    private javax.swing.JTextField jTextFieldProjetoCliente;
    private javax.swing.JTextField jTextFieldProjetoCodigo;
    private javax.swing.JTextField jTextFieldProjetoNome;
    private javax.swing.JTextField jTextFieldProjetoValorTotal;
    // End of variables declaration//GEN-END:variables
}
