package business;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thebell
 */
public class EditarOrcamento extends javax.swing.JFrame {

    private final int index;
    private final Orcamento orcamento;
    private final ArrayList<Orcamento> orcamentos;

    
    public EditarOrcamento(int index, ArrayList<Orcamento> orcamentos) {
        this.index = index;
        this.orcamento = orcamentos.get(index);
        this.orcamentos = orcamentos;
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNovoOrcamento = new javax.swing.JPanel();
        jScrollPaneNovoOrcamento = new javax.swing.JScrollPane();
        jPanelNovoOrcamentoConteudo = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jTextFieldOrcamentoProjeto = new javax.swing.JTextField();
        jLabel99 = new javax.swing.JLabel();
        jTextFieldOrcamentoCodigo = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        jTextFieldOrcamentoCliente = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaOrcamentodescricao = new javax.swing.JTextArea();
        jLabel107 = new javax.swing.JLabel();
        jTextFieldOrcamentoValor = new javax.swing.JTextField();
        jButtonOrcamentoSalvar = new javax.swing.JButton();
        jButtonOrcamentoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Material"));

        jLabel97.setText("Projeto");

        jTextFieldOrcamentoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrcamentoProjetoActionPerformed(evt);
            }
        });

        jLabel99.setText("Código");

        jTextFieldOrcamentoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrcamentoCodigoActionPerformed(evt);
            }
        });

        jLabel101.setText("Cliente");

        jTextFieldOrcamentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrcamentoClienteActionPerformed(evt);
            }
        });

        jLabel106.setText("Descrição");

        jTextAreaOrcamentodescricao.setColumns(20);
        jTextAreaOrcamentodescricao.setRows(5);
        jScrollPane9.setViewportView(jTextAreaOrcamentodescricao);

        jLabel107.setText("Valor");

        jTextFieldOrcamentoValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrcamentoValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel101)
                    .addComponent(jLabel97)
                    .addComponent(jLabel106)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOrcamentoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOrcamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel107)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel105))
                            .addComponent(jLabel99)
                            .addComponent(jTextFieldOrcamentoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jTextFieldOrcamentoValor)))
                    .addComponent(jScrollPane9))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel97)
                    .addComponent(jLabel99))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrcamentoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOrcamentoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel101)
                    .addComponent(jLabel105)
                    .addComponent(jLabel107))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOrcamentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOrcamentoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonOrcamentoSalvar.setText("Salvar");
        jButtonOrcamentoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOrcamentoSalvarMouseClicked(evt);
            }
        });
        jButtonOrcamentoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrcamentoSalvarActionPerformed(evt);
            }
        });

        jButtonOrcamentoCancelar.setText("Cancelar");
        jButtonOrcamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrcamentoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNovoOrcamentoConteudoLayout = new javax.swing.GroupLayout(jPanelNovoOrcamentoConteudo);
        jPanelNovoOrcamentoConteudo.setLayout(jPanelNovoOrcamentoConteudoLayout);
        jPanelNovoOrcamentoConteudoLayout.setHorizontalGroup(
            jPanelNovoOrcamentoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNovoOrcamentoConteudoLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelNovoOrcamentoConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonOrcamentoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOrcamentoCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNovoOrcamentoConteudoLayout.setVerticalGroup(
            jPanelNovoOrcamentoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoOrcamentoConteudoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNovoOrcamentoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrcamentoSalvar)
                    .addComponent(jButtonOrcamentoCancelar))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jScrollPaneNovoOrcamento.setViewportView(jPanelNovoOrcamentoConteudo);

        javax.swing.GroupLayout jPanelNovoOrcamentoLayout = new javax.swing.GroupLayout(jPanelNovoOrcamento);
        jPanelNovoOrcamento.setLayout(jPanelNovoOrcamentoLayout);
        jPanelNovoOrcamentoLayout.setHorizontalGroup(
            jPanelNovoOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        jPanelNovoOrcamentoLayout.setVerticalGroup(
            jPanelNovoOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoOrcamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNovoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNovoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOrcamentoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrcamentoProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrcamentoProjetoActionPerformed

    private void jTextFieldOrcamentoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrcamentoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrcamentoCodigoActionPerformed

    private void jTextFieldOrcamentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrcamentoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrcamentoClienteActionPerformed

    private void jTextFieldOrcamentoValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrcamentoValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrcamentoValorActionPerformed

    private void jButtonOrcamentoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrcamentoSalvarMouseClicked

        if (jTextFieldOrcamentoProjeto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuOrcamento();
        } else if (jTextFieldOrcamentoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuOrcamento();
        } else if (jTextFieldOrcamentoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuOrcamento();
        } else if (jTextAreaOrcamentodescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuOrcamento();
        } else if (jTextFieldOrcamentoValor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuOrcamento();
        } else {

            orcamento.setProjeto(jTextFieldOrcamentoProjeto.getText());
            orcamento.setCodigo(Integer.parseInt(jTextFieldOrcamentoCodigo.getText()));
            orcamento.setCliente(jTextFieldOrcamentoCliente.getText());
            orcamento.setValorProjeto(Double.parseDouble(jTextFieldOrcamentoValor.getText()));
            orcamento.setDetalhamentoCusto(jTextAreaOrcamentodescricao.getText());

            orcamentos.remove(index);
            orcamentos.add(index, orcamento);
            Orcamento.escrever(orcamentos);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
            dispose();

        }
    }//GEN-LAST:event_jButtonOrcamentoSalvarMouseClicked

    private void jButtonOrcamentoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrcamentoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrcamentoSalvarActionPerformed

    private void jButtonOrcamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrcamentoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonOrcamentoCancelarActionPerformed
     /**
     * Método para limpar os campos dp menu orçamento
     */
    private void limparMenuOrcamento() {
        jTextFieldOrcamentoProjeto.setText("");
        jTextFieldOrcamentoCliente.setText("");
        jTextFieldOrcamentoCodigo.setText("");
        jTextFieldOrcamentoValor.setText("");
        jTextAreaOrcamentodescricao.setText("");
    }
    /**
     * Método para preencher os campos do menu com os dados do orçamento
     */
    private void mostrar() {
        jTextFieldOrcamentoCliente.setText(orcamento.getCliente());
        jTextFieldOrcamentoCodigo.setText(String.valueOf(orcamento.getCodigo()));
        jTextFieldOrcamentoProjeto.setText(orcamento.getProjeto());
        jTextFieldOrcamentoValor.setText(String.valueOf(orcamento.getValorProjeto()));
        jTextAreaOrcamentodescricao.setText(orcamento.getDetalhamentoCusto());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOrcamentoCancelar;
    private javax.swing.JButton jButtonOrcamentoSalvar;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanelNovoOrcamento;
    private javax.swing.JPanel jPanelNovoOrcamentoConteudo;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneNovoOrcamento;
    private javax.swing.JTextArea jTextAreaOrcamentodescricao;
    private javax.swing.JTextField jTextFieldOrcamentoCliente;
    private javax.swing.JTextField jTextFieldOrcamentoCodigo;
    private javax.swing.JTextField jTextFieldOrcamentoProjeto;
    private javax.swing.JTextField jTextFieldOrcamentoValor;
    // End of variables declaration//GEN-END:variables
}
