/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package business;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thebell
 */
public class EditarContrato extends javax.swing.JFrame {

    private final int index;
    private final Contrato contrato;
    private final ArrayList<Contrato> contratos;

    /**
     * Creates new form EditarContrato
     */
    public EditarContrato(int index, ArrayList<Contrato> contratos) {
        this.index = index;
        this.contrato = contratos.get(index);
        this.contratos = contratos;
        initComponents();
        mostrar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNovoContrato = new javax.swing.JPanel();
        jScrollPaneNovoContrato = new javax.swing.JScrollPane();
        jPanelNovoContratoConteudo = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jTextFieldContratoCodigo = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jTextFieldContratoCusto = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jTextFieldContratoValorTotal = new javax.swing.JTextField();
        jComboBoxContratoFuncionario = new javax.swing.JComboBox<>();
        jLabel114 = new javax.swing.JLabel();
        jComboBoxContratoProjeto = new javax.swing.JComboBox<>();
        jLabel116 = new javax.swing.JLabel();
        jComboBoxContratoOrcamento = new javax.swing.JComboBox<>();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jTextFieldContratoDataInicio = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jTextFieldContratoDataTermino = new javax.swing.JTextField();
        jButtonContratoSalvar = new javax.swing.JButton();
        jButtonContratoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Contrato"));

        jLabel109.setText("Código");

        jLabel110.setText("Imagem");

        jTextFieldContratoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratoCodigoActionPerformed(evt);
            }
        });

        jLabel111.setText("Custo do material");

        jLabel112.setText("Imagem");

        jTextFieldContratoCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratoCustoActionPerformed(evt);
            }
        });

        jLabel113.setText("Funcionário");

        jLabel117.setText("Valor");

        jLabel118.setText("Imagem");

        jTextFieldContratoValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratoValorTotalActionPerformed(evt);
            }
        });

        jComboBoxContratoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o funcionario" }));
        jComboBoxContratoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContratoFuncionarioMouseClicked(evt);
            }
        });

        jLabel114.setText("Projeto");

        jComboBoxContratoProjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o projeto" }));
        jComboBoxContratoProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContratoProjetoMouseClicked(evt);
            }
        });

        jLabel116.setText("Orçamento");

        jComboBoxContratoOrcamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o orçamento" }));
        jComboBoxContratoOrcamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxContratoOrcamentoMouseClicked(evt);
            }
        });

        jLabel119.setText("Data início");

        jLabel120.setText("Imagem");

        jTextFieldContratoDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratoDataInicioActionPerformed(evt);
            }
        });

        jLabel121.setText("Data término");

        jLabel122.setText("Imagem");

        jTextFieldContratoDataTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContratoDataTerminoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContratoDataInicio)
                .addGap(52, 52, 52)
                .addComponent(jLabel122)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContratoDataTermino)
                .addGap(33, 33, 33))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel113)
                            .addComponent(jLabel109)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel110)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldContratoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel111)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel117)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel115))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel112)
                                    .addComponent(jLabel118))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldContratoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContratoValorTotal)))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxContratoFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel114)
                            .addComponent(jComboBoxContratoProjeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(167, 167, 167)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel116)
                            .addComponent(jComboBoxContratoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel119)
                        .addGap(308, 308, 308)
                        .addComponent(jLabel121)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109)
                    .addComponent(jLabel111))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(jTextFieldContratoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112)
                    .addComponent(jTextFieldContratoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel113)
                    .addComponent(jLabel115)
                    .addComponent(jLabel117))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel118)
                    .addComponent(jTextFieldContratoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContratoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel114)
                    .addComponent(jLabel116))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxContratoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxContratoOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel119)
                    .addComponent(jLabel121))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel120)
                    .addComponent(jTextFieldContratoDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel122)
                    .addComponent(jTextFieldContratoDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButtonContratoSalvar.setText("Salvar");
        jButtonContratoSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContratoSalvarMouseClicked(evt);
            }
        });
        jButtonContratoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratoSalvarActionPerformed(evt);
            }
        });

        jButtonContratoCancelar.setText("Cancelar");
        jButtonContratoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContratoCancelarMouseClicked(evt);
            }
        });
        jButtonContratoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNovoContratoConteudoLayout = new javax.swing.GroupLayout(jPanelNovoContratoConteudo);
        jPanelNovoContratoConteudo.setLayout(jPanelNovoContratoConteudoLayout);
        jPanelNovoContratoConteudoLayout.setHorizontalGroup(
            jPanelNovoContratoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoContratoConteudoLayout.createSequentialGroup()
                .addGroup(jPanelNovoContratoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNovoContratoConteudoLayout.createSequentialGroup()
                        .addComponent(jButtonContratoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonContratoCancelar)))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        jPanelNovoContratoConteudoLayout.setVerticalGroup(
            jPanelNovoContratoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoContratoConteudoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanelNovoContratoConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContratoSalvar)
                    .addComponent(jButtonContratoCancelar))
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jScrollPaneNovoContrato.setViewportView(jPanelNovoContratoConteudo);

        javax.swing.GroupLayout jPanelNovoContratoLayout = new javax.swing.GroupLayout(jPanelNovoContrato);
        jPanelNovoContrato.setLayout(jPanelNovoContratoLayout);
        jPanelNovoContratoLayout.setHorizontalGroup(
            jPanelNovoContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        jPanelNovoContratoLayout.setVerticalGroup(
            jPanelNovoContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNovoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNovoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContratoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratoCodigoActionPerformed

    private void jTextFieldContratoCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratoCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratoCustoActionPerformed

    private void jTextFieldContratoValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratoValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratoValorTotalActionPerformed

    private void jComboBoxContratoFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContratoFuncionarioMouseClicked
        ArrayList<Funcionario> funcionarios = Funcionario.ler();
        jComboBoxContratoFuncionario.removeAllItems();

        for (int i = 0; i < funcionarios.size(); i++) {
            jComboBoxContratoFuncionario.addItem(funcionarios.get(i).getNome());
        }
    }//GEN-LAST:event_jComboBoxContratoFuncionarioMouseClicked

    private void jComboBoxContratoProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContratoProjetoMouseClicked
        ArrayList<Projeto> projetos = Projeto.ler();
        jComboBoxContratoProjeto.removeAllItems();

        for (int i = 0; i < projetos.size(); i++) {
            jComboBoxContratoProjeto.addItem(projetos.get(i).getNome());
        }
    }//GEN-LAST:event_jComboBoxContratoProjetoMouseClicked

    private void jComboBoxContratoOrcamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxContratoOrcamentoMouseClicked
        ArrayList<Orcamento> orcamentos = Orcamento.ler();
        jComboBoxContratoOrcamento.removeAllItems();

        for (int i = 0; i < orcamentos.size(); i++) {
            jComboBoxContratoOrcamento.addItem(orcamentos.get(i).getProjeto());
        }
    }//GEN-LAST:event_jComboBoxContratoOrcamentoMouseClicked

    private void jTextFieldContratoDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratoDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratoDataInicioActionPerformed

    private void jTextFieldContratoDataTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContratoDataTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContratoDataTerminoActionPerformed

    private void jButtonContratoSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContratoSalvarMouseClicked
        if (jTextFieldContratoCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldContratoCusto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldContratoDataInicio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldContratoDataTermino.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else if (jTextFieldContratoValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        } else {

            contrato.setCodigo(Integer.parseInt(jTextFieldContratoCodigo.getText()));
            contrato.setCustoMaterial(Double.parseDouble(jTextFieldContratoCusto.getText()));
            contrato.setValorTotal(Double.parseDouble(jTextFieldContratoValorTotal.getText()));
            contrato.setDataInicio(jTextFieldContratoDataInicio.getText());
            contrato.setDataTermino(jTextFieldContratoDataTermino.getText());
            Contrato.escrever(contrato, contrato.ler());
            contrato.setProjeto(jComboBoxContratoProjeto.getItemAt(jComboBoxContratoProjeto.getSelectedIndex()));
            contrato.setFuncionarios(jComboBoxContratoFuncionario.getItemAt(jComboBoxContratoFuncionario.getSelectedIndex()));
            contrato.setOrcamento(jComboBoxContratoOrcamento.getItemAt(jComboBoxContratoOrcamento.getSelectedIndex()));
            JOptionPane.showMessageDialog(null, "Salvo com sucesso.");
            dispose();
        }
    }//GEN-LAST:event_jButtonContratoSalvarMouseClicked

    private void jButtonContratoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContratoSalvarActionPerformed

    private void jButtonContratoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratoCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContratoCancelarActionPerformed

    private void jButtonContratoCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContratoCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jButtonContratoCancelarMouseClicked
     /**
     * Método para preencher os campos do menu com os dados do contrato
     */
    private void mostrar() {
        jTextFieldContratoCodigo.setText(String.valueOf(contrato.getCodigo()));
        jTextFieldContratoCusto.setText(String.valueOf(contrato.getCustoMaterial()));
        jTextFieldContratoValorTotal.setText(String.valueOf(contrato.getValorTotal()));
        
        jTextFieldContratoDataInicio.setText(contrato.getDataInicio().toString());
        jTextFieldContratoDataTermino.setText(contrato.getDataTermino().toString());
        jComboBoxContratoFuncionario.addItem(contrato.getFuncionarios());
        jComboBoxContratoOrcamento.addItem(contrato.getOrcamento());
        jComboBoxContratoProjeto.addItem(contrato.getProjeto());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContratoCancelar;
    private javax.swing.JButton jButtonContratoSalvar;
    private javax.swing.JComboBox<String> jComboBoxContratoFuncionario;
    private javax.swing.JComboBox<String> jComboBoxContratoOrcamento;
    private javax.swing.JComboBox<String> jComboBoxContratoProjeto;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanelNovoContrato;
    private javax.swing.JPanel jPanelNovoContratoConteudo;
    private javax.swing.JScrollPane jScrollPaneNovoContrato;
    private javax.swing.JTextField jTextFieldContratoCodigo;
    private javax.swing.JTextField jTextFieldContratoCusto;
    private javax.swing.JTextField jTextFieldContratoDataInicio;
    private javax.swing.JTextField jTextFieldContratoDataTermino;
    private javax.swing.JTextField jTextFieldContratoValorTotal;
    // End of variables declaration//GEN-END:variables
}
