package business;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thebell
 */
public class EditarFuncionario extends javax.swing.JFrame {

    private final int index;
    private final Funcionario funcionario;
    private final ArrayList<Funcionario> funcionarios;

    public EditarFuncionario(int index, ArrayList<Funcionario> funcionarios) {
        this.index = index;
        this.funcionario = funcionarios.get(index);
        this.funcionarios = funcionarios;
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEditarFuncionario = new javax.swing.JPanel();
        jScrollPaneNovoFuncionario = new javax.swing.JScrollPane();
        jPanelNovoClienteConteudo1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jTextFieldFuncionarioNome = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextFieldFuncionarioCodigo = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextFieldFuncionarioTelefone = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextFieldFuncionarioPais = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        jTextFieldFuncionarioEstado = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jTextFieldFuncionarioCidade = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jTextFieldFuncionarioRua = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTextFieldFuncionarioBairro = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextFieldFuncionarioNumero = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jTextFieldFuncionarioSalario1 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jButtonFuncionarioAdicionar = new javax.swing.JButton();
        jTextFieldFuncionarioProjetoAlocado = new javax.swing.JTextField();
        jComboBoxFuncionarioProjetos = new javax.swing.JComboBox<>();
        jButtonFuncionarioSalvar = new javax.swing.JButton();
        jButtonFuncionarioCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Funcionário"));

        jLabel57.setText("Nome");

        jTextFieldFuncionarioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioNomeActionPerformed(evt);
            }
        });

        jLabel59.setText("Código");

        jTextFieldFuncionarioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioCodigoActionPerformed(evt);
            }
        });

        jLabel61.setText("Telefone");

        jTextFieldFuncionarioTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioTelefoneActionPerformed(evt);
            }
        });

        jLabel63.setText("País");

        jTextFieldFuncionarioPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioPaisActionPerformed(evt);
            }
        });

        jLabel65.setText("Estado");

        jTextFieldFuncionarioEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioEstadoActionPerformed(evt);
            }
        });

        jLabel67.setText("Cidade");

        jTextFieldFuncionarioCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioCidadeActionPerformed(evt);
            }
        });

        jLabel69.setText("Rua");

        jTextFieldFuncionarioRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioRuaActionPerformed(evt);
            }
        });

        jLabel71.setText("Bairro");

        jTextFieldFuncionarioBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioBairroActionPerformed(evt);
            }
        });

        jLabel73.setText("Número");

        jTextFieldFuncionarioNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioNumeroActionPerformed(evt);
            }
        });

        jLabel75.setText("Salário");

        jTextFieldFuncionarioSalario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioSalario1ActionPerformed(evt);
            }
        });

        jLabel77.setText("Projeto Alocado");

        jButtonFuncionarioAdicionar.setText("Adicionar");
        jButtonFuncionarioAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFuncionarioAdicionarMouseClicked(evt);
            }
        });

        jTextFieldFuncionarioProjetoAlocado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncionarioProjetoAlocadoActionPerformed(evt);
            }
        });

        jComboBoxFuncionarioProjetos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um projeto" }));
        jComboBoxFuncionarioProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxFuncionarioProjetosMouseClicked(evt);
            }
        });
        jComboBoxFuncionarioProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionarioProjetosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel65)
                            .addComponent(jLabel73)
                            .addComponent(jTextFieldFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFuncionarioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFuncionarioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFuncionarioCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jTextFieldFuncionarioCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFuncionarioPais, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFuncionarioRua, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addComponent(jLabel71))
                        .addGap(310, 310, 310)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel59)
                            .addComponent(jLabel67)
                            .addComponent(jLabel69)
                            .addComponent(jLabel75)
                            .addComponent(jTextFieldFuncionarioSalario1)
                            .addComponent(jTextFieldFuncionarioProjetoAlocado, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel77)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jComboBoxFuncionarioProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButtonFuncionarioAdicionar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuncionarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionarioCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuncionarioTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionarioPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jLabel67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuncionarioEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionarioCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jLabel71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuncionarioRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionarioBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFuncionarioNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFuncionarioSalario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFuncionarioProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFuncionarioAdicionar)
                    .addComponent(jTextFieldFuncionarioProjetoAlocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonFuncionarioSalvar.setText("Salvar");
        jButtonFuncionarioSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFuncionarioSalvarMouseClicked(evt);
            }
        });
        jButtonFuncionarioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioSalvarActionPerformed(evt);
            }
        });

        jButtonFuncionarioCancelar.setText("Cancelar");
        jButtonFuncionarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNovoClienteConteudo1Layout = new javax.swing.GroupLayout(jPanelNovoClienteConteudo1);
        jPanelNovoClienteConteudo1.setLayout(jPanelNovoClienteConteudo1Layout);
        jPanelNovoClienteConteudo1Layout.setHorizontalGroup(
            jPanelNovoClienteConteudo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoClienteConteudo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFuncionarioSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFuncionarioCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNovoClienteConteudo1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanelNovoClienteConteudo1Layout.setVerticalGroup(
            jPanelNovoClienteConteudo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoClienteConteudo1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovoClienteConteudo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFuncionarioSalvar)
                    .addComponent(jButtonFuncionarioCancelar))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jScrollPaneNovoFuncionario.setViewportView(jPanelNovoClienteConteudo1);

        javax.swing.GroupLayout jPanelEditarFuncionarioLayout = new javax.swing.GroupLayout(jPanelEditarFuncionario);
        jPanelEditarFuncionario.setLayout(jPanelEditarFuncionarioLayout);
        jPanelEditarFuncionarioLayout.setHorizontalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanelEditarFuncionarioLayout.setVerticalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneNovoFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanelEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jPanelEditarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFuncionarioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioNomeActionPerformed

    private void jTextFieldFuncionarioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioCodigoActionPerformed

    private void jTextFieldFuncionarioTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioTelefoneActionPerformed

    private void jTextFieldFuncionarioPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioPaisActionPerformed

    private void jTextFieldFuncionarioEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioEstadoActionPerformed

    private void jTextFieldFuncionarioCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioCidadeActionPerformed

    private void jTextFieldFuncionarioRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioRuaActionPerformed

    private void jTextFieldFuncionarioBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioBairroActionPerformed

    private void jTextFieldFuncionarioNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioNumeroActionPerformed

    private void jButtonFuncionarioSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFuncionarioSalvarMouseClicked
        if (jTextFieldFuncionarioNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioPais.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioRua.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioSalario1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else if (jTextFieldFuncionarioProjetoAlocado.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
            limparMenuFuncionario();
        } else {

            funcionario.setNome(jTextFieldFuncionarioNome.getText());
            funcionario.setCodigo(Integer.parseInt(jTextFieldFuncionarioCodigo.getText()));
            funcionario.setTelefone(Integer.parseInt(jTextFieldFuncionarioTelefone.getText()));
            funcionario.setSalario(Float.parseFloat(jTextFieldFuncionarioSalario1.getText()));
            funcionario.setProjetoAlocado(jTextFieldFuncionarioProjetoAlocado.getText());
            funcionario.setEndereco(new Endereco(
                    jTextFieldFuncionarioPais.getText(),
                    jTextFieldFuncionarioEstado.getText(),
                    jTextFieldFuncionarioCidade.getText(),
                    jTextFieldFuncionarioBairro.getText(),
                    jTextFieldFuncionarioRua.getText(),
                    Integer.parseInt(jTextFieldFuncionarioNumero.getText())
            ));

            funcionarios.remove(index);
            funcionarios.add(index, funcionario);
            Funcionario.escrever(funcionarios);

            JOptionPane.showMessageDialog(null, "Salva com sucesso.");
            dispose();

        }
    }//GEN-LAST:event_jButtonFuncionarioSalvarMouseClicked
    /**
     * Método para limpar os campos dp menu funcionário
     */
    private void limparMenuFuncionario() {
        jTextFieldFuncionarioNome.setText("");
        jTextFieldFuncionarioCodigo.setText("");
        jTextFieldFuncionarioTelefone.setText("");
        jTextFieldFuncionarioPais.setText("");
        jTextFieldFuncionarioEstado.setText("");
        jTextFieldFuncionarioCidade.setText("");
        jTextFieldFuncionarioBairro.setText("");
        jTextFieldFuncionarioRua.setText("");
        jTextFieldFuncionarioNumero.setText("");
        jTextFieldFuncionarioSalario1.setText("");
        jTextFieldFuncionarioProjetoAlocado.setText("");
        jComboBoxFuncionarioProjetos.removeAllItems();
        jComboBoxFuncionarioProjetos.addItem("Selecione um projeto");
    }
     /**
     * Método para preencher os campos do menu com os dados do funcionário
     */
    private void mostrar() {
        jTextFieldFuncionarioNome.setText(funcionario.getNome());
        jTextFieldFuncionarioCodigo.setText(String.valueOf(funcionario.getCodigo()));
        jTextFieldFuncionarioTelefone.setText(String.valueOf(funcionario.getTelefone()));
        jTextFieldFuncionarioPais.setText(funcionario.getEndereco().getPais());
        jTextFieldFuncionarioEstado.setText(funcionario.getEndereco().getEstado());
        jTextFieldFuncionarioCidade.setText(funcionario.getEndereco().getCidade());
        jTextFieldFuncionarioBairro.setText(funcionario.getEndereco().getBairro());
        jTextFieldFuncionarioRua.setText(funcionario.getEndereco().getRua());
        jTextFieldFuncionarioNumero.setText(String.valueOf(funcionario.getEndereco().getNumero()));
        jTextFieldFuncionarioSalario1.setText(String.valueOf(funcionario.getSalario()));
        jTextFieldFuncionarioProjetoAlocado.setText(funcionario.getProjetoAlocado());
        
    }
    private void jButtonFuncionarioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFuncionarioSalvarActionPerformed

    private void jButtonFuncionarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFuncionarioCancelarActionPerformed

    private void jTextFieldFuncionarioSalario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioSalario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioSalario1ActionPerformed

    private void jTextFieldFuncionarioProjetoAlocadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncionarioProjetoAlocadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncionarioProjetoAlocadoActionPerformed

    private void jComboBoxFuncionarioProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioProjetosMouseClicked
        ArrayList<Projeto> projetos = Projeto.ler();
        jComboBoxFuncionarioProjetos.removeAllItems();
        
        for (int i = 0; i < projetos.size(); i++) {
            jComboBoxFuncionarioProjetos.addItem(projetos.get(i).getNome());
        }
    }//GEN-LAST:event_jComboBoxFuncionarioProjetosMouseClicked

    private void jButtonFuncionarioAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFuncionarioAdicionarMouseClicked
        if (jComboBoxFuncionarioProjetos.getSelectedIndex() != -1) {
            jTextFieldFuncionarioProjetoAlocado.setText(jComboBoxFuncionarioProjetos.getItemAt(
            jComboBoxFuncionarioProjetos.getSelectedIndex()));
        }
    }//GEN-LAST:event_jButtonFuncionarioAdicionarMouseClicked

    private void jComboBoxFuncionarioProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioProjetosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFuncionarioProjetosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncionarioAdicionar;
    private javax.swing.JButton jButtonFuncionarioCancelar;
    private javax.swing.JButton jButtonFuncionarioSalvar;
    private javax.swing.JComboBox<String> jComboBoxFuncionarioProjetos;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelEditarFuncionario;
    private javax.swing.JPanel jPanelNovoClienteConteudo1;
    private javax.swing.JScrollPane jScrollPaneNovoFuncionario;
    private javax.swing.JTextField jTextFieldFuncionarioBairro;
    private javax.swing.JTextField jTextFieldFuncionarioCidade;
    private javax.swing.JTextField jTextFieldFuncionarioCodigo;
    private javax.swing.JTextField jTextFieldFuncionarioEstado;
    private javax.swing.JTextField jTextFieldFuncionarioNome;
    private javax.swing.JTextField jTextFieldFuncionarioNumero;
    private javax.swing.JTextField jTextFieldFuncionarioPais;
    private javax.swing.JTextField jTextFieldFuncionarioProjetoAlocado;
    private javax.swing.JTextField jTextFieldFuncionarioRua;
    private javax.swing.JTextField jTextFieldFuncionarioSalario1;
    private javax.swing.JTextField jTextFieldFuncionarioTelefone;
    // End of variables declaration//GEN-END:variables
}
