
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author diego
 */
public class TelaCadastroUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUser
     *
     * @param tl
     */
    public TelaCadastroUser(TelaLogin tl) {
        initComponents();
        this.telaLoginTemp = tl;
        this.telaLoginTemp.setVisible(false);

    }
    private TelaLogin telaLoginTemp;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaCadastroUser = new javax.swing.JPanel();
        jTextFieldCadastroUser = new javax.swing.JTextField();
        jPasswordFieldCadastroUser = new javax.swing.JPasswordField();
        jButtonCadastrarUser = new javax.swing.JButton();
        jLabelSenha = new javax.swing.JLabel();
        jLabelNomeUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar novo usuário");
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);

        jPanelTelaCadastroUser.setPreferredSize(new java.awt.Dimension(300, 400));

        jTextFieldCadastroUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCadastroUser.setPreferredSize(new java.awt.Dimension(200, 35));

        jPasswordFieldCadastroUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldCadastroUser.setPreferredSize(new java.awt.Dimension(200, 35));

        jButtonCadastrarUser.setText("Cadastrar");
        jButtonCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarUserActionPerformed(evt);
            }
        });

        jLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSenha.setText("Senha");
        jLabelSenha.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabelNomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeUser.setText("Nome do usuário");
        jLabelNomeUser.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout jPanelTelaCadastroUserLayout = new javax.swing.GroupLayout(jPanelTelaCadastroUser);
        jPanelTelaCadastroUser.setLayout(jPanelTelaCadastroUserLayout);
        jPanelTelaCadastroUserLayout.setHorizontalGroup(
            jPanelTelaCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                .addGroup(jPanelTelaCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelTelaCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButtonCadastrarUser))
                    .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jPanelTelaCadastroUserLayout.setVerticalGroup(
            jPanelTelaCadastroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaCadastroUserLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jTextFieldCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPasswordFieldCadastroUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButtonCadastrarUser)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTelaCadastroUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTelaCadastroUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarUserActionPerformed
        // TODO add your handling code here:
        gravarLogin();
    }//GEN-LAST:event_jButtonCadastrarUserActionPerformed

    private boolean gravarLogin() {
        File file = new File("Data/login.dat");
        try {
            FileOutputStream fos = new FileOutputStream(file);
            ObjectOutputStream output = new ObjectOutputStream(fos);
            output.writeObject(new DadosLogin(jTextFieldCadastroUser.getText(), new String(jPasswordFieldCadastroUser.getPassword())));
            output.flush();
            output.close();
            this.telaLoginTemp.setVisible(true);
            this.dispose();
            return true;
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarUser;
    private javax.swing.JLabel jLabelNomeUser;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanelTelaCadastroUser;
    private javax.swing.JPasswordField jPasswordFieldCadastroUser;
    private javax.swing.JTextField jTextFieldCadastroUser;
    // End of variables declaration//GEN-END:variables
}
