/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class TelaEsqueciSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaEsqueciSenha
     */
    private TelaLogin telaEsqTemp = null;

    public TelaEsqueciSenha(TelaLogin tl) {
        this.telaEsqTemp = tl;
        this.telaEsqTemp.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRecuperarDados = new javax.swing.JPanel();
        jButtonRecuperarDados = new javax.swing.JButton();
        jTextFieldRecuperarDados = new javax.swing.JTextField();
        jButtonCancelarRecover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar dados");
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);

        jPanelRecuperarDados.setBackground(new java.awt.Color(254, 254, 254));
        jPanelRecuperarDados.setPreferredSize(new java.awt.Dimension(300, 400));

        jButtonRecuperarDados.setText("Confirmar");
        jButtonRecuperarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRecuperarDados.setPreferredSize(new java.awt.Dimension(100, 35));
        jButtonRecuperarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecuperarDadosActionPerformed(evt);
            }
        });

        jTextFieldRecuperarDados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRecuperarDados.setPreferredSize(new java.awt.Dimension(200, 35));

        jButtonCancelarRecover.setText("Cancelar");
        jButtonCancelarRecover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelarRecover.setPreferredSize(new java.awt.Dimension(100, 35));
        jButtonCancelarRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarRecoverActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPF");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jPanelRecuperarDadosLayout = new javax.swing.GroupLayout(jPanelRecuperarDados);
        jPanelRecuperarDados.setLayout(jPanelRecuperarDadosLayout);
        jPanelRecuperarDadosLayout.setHorizontalGroup(
            jPanelRecuperarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecuperarDadosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelRecuperarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRecuperarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRecuperarDadosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelRecuperarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelarRecover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRecuperarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelRecuperarDadosLayout.setVerticalGroup(
            jPanelRecuperarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRecuperarDadosLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldRecuperarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonRecuperarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonCancelarRecover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRecuperarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelRecuperarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarRecoverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.telaEsqTemp.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarRecoverActionPerformed

    private void jButtonRecuperarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecuperarDadosActionPerformed
        // TODO add your handling code here:
        if (jTextFieldRecuperarDados.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Existem campos em branco!", "Falha", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (Login.lerLogin() == null) {
                JOptionPane.showMessageDialog(null, "O sistema não possui administrador cadastrado!", "Falha",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                long cpf = (Long.parseLong(jTextFieldRecuperarDados.getText()));
                if (Login.lerLogin().getCPF() == cpf) {
                    this.setVisible(false);
                    Login.restaurar(cpf, telaEsqTemp);
                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(null, "CPF inválido!", "Falha",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonRecuperarDadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarRecover;
    private javax.swing.JButton jButtonRecuperarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelRecuperarDados;
    private javax.swing.JTextField jTextFieldRecuperarDados;
    // End of variables declaration//GEN-END:variables
}
